### ISSUE TITLE
Unconditional Diffusion Model for generating 1D biosignals

### ISSUE THREAD

**Issue by OmegaAsh** [imics-lab/biodiffusion#1]
Hi guys, I am interested in using this for my project (will be sure to cite) to generate synthetic 1-channel PPG data for downstream tasks. Just wondering if there is some way to generate the 1D signals unconditionally using this repository, as I can only see 1D signal-conditioned and label-conditioned implementations. Asking as there is an unconditional Diffusion model also mentioned in the paper.

Thanks,

**Comment by smiksha1701** [comment]
Hello,
Sorry for a bit late response.

> Just wondering if there is some way to generate the 1D signals unconditionally using this repository, as I can only see 1D signal-conditioned and label-conditioned implementations

You can train Classifier free DDPM model using [this file](https://github.com/imics-lab/biodiffusion/blob/main/src/signal/ddpm1d_cls_free.py). Specifically if you need to generate unconditionally - you need to set `cond_scale=0`

```
diffusion.sample(classes = signal_classes, cond_scale = 0)      
```
 If you do so classes passed for conditioning will be omitted and model will be generating signals unconditionally(to read how it works please see this [paper](https://openreview.net/pdf?id=qw8AKxfYbI)).

**Comment by smiksha1701** [comment]
Closing issue with no further questions

**Comment by smiksha1701** [comment]
> Closing issue with no further questions
